[versions]
slf4j = "2.0.18"
jakarta-validation = "3.1.1"
jspecify = "1.0.0"
junit = "5.10.0"
hibernate-validator = "9.1.0.Final"
mockito = "5.23.0"
assertj = "3.27.7"
expressly = "6.0.0"
vanniktech-publish = "0.34.0"
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
spring-web = "6.2.7"
tika = "3.3.1"
pdfbox = "3.0.7"
micrometer = "1.17.0"
aws-sdk = "2.46.15"
jackson = "2.21"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
hibernate-validator = { module = "org.hibernate.validator:hibernate-validator", version.ref = "hibernate-validator" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
expressly = { module = "org.glassfish.expressly:expressly", version.ref = "expressly" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring-web" }
spring-webflux = { module = "org.springframework:spring-webflux", version.ref = "spring-web" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "spring-boot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
tika-core = { module = "org.apache.tika:tika-core", version.ref = "tika" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
micrometer-test = { module = "io.micrometer:micrometer-test", version.ref = "micrometer" }
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws-sdk" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }

[plugins]
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
